# Generated by Django 3.1.1 on 2020-09-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drawings',
            field=models.JSONField(default=dict),
        ),
    ]
